---

#########################################################
## Vault module for server config                      ##
#########################################################
# secret engine name (vault_name): devices
# secret engine type: kv
# secret name: variable server_vault_id, default '{{ ansible_fqdn | replace('.', '-') }}'

# Validate variables
- name: Validate required variables for action.
  ansible.builtin.assert:
    that: "item is defined"
    fail_msg: "Required variable '{{ item }}' has not been provided."
    quiet: true
  with_items:
    - vault_address
    - vault_token

# Register variable (_vault_name) 
- name: Register variable (vault_name)...
  ansible.builtin.set_fact:
   _vault_name: "{{ server_vault_name | default('devices') }}"

# Register variable (_secret_name)
- name: Register variable (secret_name)...
  ansible.builtin.set_fact:
    _secret_name: "{{ server_vault_id | default( ansible_fqdn | replace('.', '-')) }}"

#########################################################
## Secret Engine (devices)                             ##
#########################################################

# Create secret engine
- name: Create secret engine...
  ansible.builtin.include_role:
    name: vault
    tasks_from: secret_engine.yml
  vars:
    action: create_secret_engine
    vault_name: "{{ _vault_name }}"
    vault_description: "{{ server_vault_description | default('Secrets for devices') }}"
    vault_type: "kv"

#########################################################
## Secrets (fqdn)                                      ##
#########################################################

# Declare variable _secret_keyvalue
- name: Register variable (secret_keyvalue)...
  ansible.builtin.set_fact:
    _secret_keyvalue: |
      admin_username: '{{ admin_username | default('admin') }}'
      admin_password: '{{ admin_password | default('') }}'
      automation_username: '{{ automation_username | default('ansible') }}'
      automation_password: '{{ automation_password | default('') }}'
      automation_email: '{{ automation_email | default('ansible@{{ ansible_fqdn }}') }}'

# Store usernames and passwords in Hashicorp Vault.
- name: "Store {{ ansible_fqdn }} usernames and passwords in Vault"
  ansible.builtin.include_role:
    name: vault
    tasks_from: secrets.yml
  vars:
    action: create_secret
    vault_name: "{{ _vault_name }}"
    secret_name: "{{ _secret_name }}"
    secret_keyvalue: "{{ _secret_keyvalue | from_yaml }}"

#########################################################
## Post-configure                                      ##
#########################################################

# Unset variables
- name: Unset variables...
  ansible.builtin.set_fact:
    _vault_name: null
    _secret_name: null
    _secret_keyvalue: null
