---

#########################################################
## Pre-installation                                    ##
#########################################################

#########################################################
## Network configuration                               ##
#########################################################

# Set hostname
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ server_hostname }}"
  when: server_hostname is defined

# Set timezone 
- name: "Set timezone to {{ timezone }}"
  community.general.timezone:
    name: "{{ timezone }}"

# Install packages
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nano
    - git
