---

#########################################################
## Configure repo module                               ##
#########################################################
# This module will configure the OS repo.
# repo_name: filename of repo configuration
# repo_base_url: base URL of the repo

# Validate variables
- name: Validate required variables for action...
  ansible.builtin.assert:
    that: "item is defined"
    fail_msg: "Required variable '{{ item }}' has not been provided."
    quiet: true
  with_items:
    - repo_name
    - repo_base_url

# stat the existing yum repo file(s)
- name: "Gather OS repository information rocky.repo..."
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/rocky.repo"
  register: repofile

# Copy file to new file in the same location
- name: "Move rocky.repo to rocky.repo_not..."
  become: true
  ansible.builtin.copy:
    src: "/etc/yum.repos.d/rocky.repo"
    dest: "/etc/yum.repos.d/rocky.repo_not"
    remote_src: yes
  when: repofile.stat.exists

# Remove original file 
- name: "Remove rocky.repo..."
  become: true
  ansible.builtin.file:
    path: "/etc/yum.repos.d/rocky.repo"
    state: absent
  when: repofile.stat.exists

# Create repository file for local Nexus3 serviced yum repositories
- name: Create OS repo configuration...
  become: true
  ansible.builtin.template:
    src: repo_local_template.j2
    dest: /etc/yum.repos.d/{{ repo_name }}
  