---

#########################################################
## Vault module                                        ##
#########################################################

# Validate variables
- name: Validate required variables for action.
  ansible.builtin.assert:
    that: "item is defined"
    fail_msg: "Required variable '{{ item }}' has not been provided."
    quiet: true
  with_items:
    - vault_address
    - vault_token

#########################################################
## Configuration Vault KV                              ##
#########################################################

# Clear variable, be sure it is not used from a previous run.
- name: Clear variable vault_name
  ansible.builtin.set_fact:
    vault_name: ""
  no_log: true

# Clear variable, be sure it is not used from a previous run.
- name: Clear variable vault_description
  ansible.builtin.set_fact:
    vault_description: ""
  no_log: true

# Create secret engine
- name: Create secret engine
  ansible.builtin.include_role:
    name: vault
    tasks_from: secret_engine.yml
  vars:
    action: create_secret_engine
    vault_name: "devices"
    vault_description: "Secrets for various devices"
    vault_type: "kv"

#########################################################
## Configuration secrets                               ##
#########################################################

# Set variable if not defined
- name: Set variable (admin_username)...
  ansible.builtin.set_fact:
    admin_username: "admin"
  when: admin_username is not defined

# Set variable if not defined
- name: Set variable (admin_password)...
  ansible.builtin.set_fact:
    admin_password: ""
  when: admin_password is not defined

# Set variable if not defined
- name: Set variable (automation_username)...
  ansible.builtin.set_fact:
    automation_username: "ansible"
  when: automation_username is not defined

# Set variable if not defined
- name: Set variable (automation_password)...
  ansible.builtin.set_fact:
    automation_password: ""
  when: automation_password is not defined

# Set variable if not defined
- name: Set variable (automation_email)...
  ansible.builtin.set_fact:
    automation_email: "ansible@{{ ansible_fqdn }}"
  when: automation_email is not defined

# Declare variable _secret_keyvalue
- name: Register variable (secret_keyvalue)...
  ansible.builtin.set_fact:
    _secret_keyvalue: |
      admin_username: '{{ admin_username }}'
      admin_password: '{{ admin_password }}'
      automation_username: '{{ automation_username }}'
      automation_password: '{{ automation_password }}'
      automation_email: '{{ automation_email }}'

# Store usernames and passwords in Hashicorp Vault.
- name: "Store {{ ansible_fqdn }} usernames and passwords in Vault"
  ansible.builtin.include_role:
    name: vault
    tasks_from: secrets.yml
  vars:
    action: create_secret
    vault_name: "devices"
    secret_name: "{{ ansible_fqdn | replace('.', '-') }}"
    secret_keyvalue: "{{ _secret_keyvalue | from_yaml }}"

#########################################################
## Post-configure                                      ##
#########################################################

# Unset variables
- name: Unset variables...
  ansible.builtin.set_fact:
    admin_password:
