---

#########################################################
## first_config module                                 ##
#########################################################
# first config sets the hostname, timezone, and checks the ansible version.
# recommended ansible version is 2.18+
# to install ansible 2.18+ use the following command: pip install ansible==2.18

# Validate global variables
- name: Validate required variables for server configuration module...
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - server_hostname

# Register global variable
- name: Register global variable (server_hostname)...
  ansible.builtin.set_fact:
    server_hostname: "{{ server_hostname }}"

# Test for ansible version, recommended version is 2.18+, show warning if version is lower
- name: Test for ansible version...
  ansible.builtin.assert:
    that: "ansible_version.full is version('2.15', '>=')"
    fail_msg: "Ansible version is lower than 2.15. Recommended version is 2.15+"
    quiet: true

#########################################################
## Network configuration                               ##
#########################################################

# Set hostname
- name: "Set hostname to {{ server_hostname }}..."
  become: true
  ansible.builtin.hostname:
    name: "{{ server_hostname }}"
  when: server_hostname is defined

# Set timezone
- name: "Set timezone to {{ timezone }}..."
  become: true
  ansible.builtin.command:
    cmd: "timedatectl set-timezone {{ timezone }}"
  when: timezone is defined

#########################################################
## Packages configuration                              ##
#########################################################

# Information message
- name: Information message...
  ansible.builtin.debug:
    msg: "Installing required packages, this may take a while..."
 
# Install Python packages
# passlib required to set password when creating users
- name: Install required Python packages...
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - passlib

#########################################################
## Post-config                                         ##
#########################################################
