---

#########################################################
## first_config module                                 ##
#########################################################

# Validate global variables
- name: Validate required variables for server configuration module...
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - server_hostname

# Register global variable
- name: Register global variable (server_hostname)...
  ansible.builtin.set_fact:
    server_hostname: "{{ server_hostname }}"

#########################################################
## Network configuration                               ##
#########################################################

# Set hostname
- name: "Set hostname to {{ server_hostname }}..."
  become: true
  ansible.builtin.hostname:
    name: "{{ server_hostname }}"
  when: server_hostname is defined

# Set timezone
- name: "Set timezone to {{ timezone }}..."
  become: true
  ansible.builtin.command:
    cmd: "timedatectl set-timezone {{ timezone }}"
  when: timezone is defined

#########################################################
## Packages configuration                              ##
#########################################################

# Information message
- name: Information message...
  ansible.builtin.debug:
    msg: "Installing required packages, this may take a while..."

# Install packages
- name: Install required system packages...
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nano
    - git
    - tar
    - python3-pip
  

# Install Python packages
- name: Install required Python packages...
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - passlib

#########################################################
## Post-config                                         ##
#########################################################
