---

#########################################################
## first_config module                                 ##
#########################################################

# Validate global variables
- name: Validate required variables for Sonatype Nexus administration module...
  ansible.builtin.assert:
    that: "varitem is defined"
    fail_msg: "Required variable '{{ varitem }}' has not been provided."
    quiet: true
  loop_control:
    loop_var: varitem
  loop:
    - server_hostname

#########################################################
## Network configuration                               ##
#########################################################

# Set hostname
- name: "Set hostname to {{ server_hostname }}..."
  ansible.builtin.hostname:
    name: "{{ server_hostname }}"
  when: server_hostname is defined

# Set timezone
- name: "Set timezone to {{ timezone }}..."
  community.general.timezone:
    name: "{{ timezone }}"
  when: timezone is defined

# Remove IPv6 from host file
# TODO

# Install packages
- name: Install required packages...
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - nano
    - git
