---

# Show message
- name: Show action message
  debug:
    msg: "Starting role {{ role_name }}... action: {{ action }}."

# If action variable is not defined, gather status of the service and set action variable
- name: Gather action variable status...
  ansible.builtin.include_tasks: get_status.yml
  when: action is not defined

# Assert that action is in actions
- name: "Verify valid action ({{ action }})..."
  ansible.builtin.assert:
    that:
      - action in (actions | map('dict2items') | map('first') | map(attribute='key') | list)
    fail_msg: "The action '{{ action }}' is not in the list of valid actions..."
    quiet: true
# -------------------------------------------------------

- name: Start first_config action...
  ansible.builtin.include_tasks: first_config.yml
  when: action == "first_config"

- name: Start configure_server action...
  ansible.builtin.include_tasks: configure_server.yml
  when: action == "configure_server"

- name: Start configure_vault action...
  ansible.builtin.include_tasks: configure_vault.yml
  when: action == "configure_vault"

- name: Start initialize action...
  ansible.builtin.include_tasks: initialize.yml
  when: action == "initialize"

