---

# Show message
- name: Show action message
  debug:
    msg: "Starting role {{ role_name }}... action: {{ action }}."

# If action variable is not defined, gather status of the service and set action variable
- name: Gather action variable status...
  ansible.builtin.include_tasks: get_status.yml
  when: action is not defined

- name: "Verify valid action {{ action }}..."
  ansible.builtin.assert:
    that:
      - action is defined and action in actions
    fail_msg: "Please provide 'action' {{ actions }}"
    quiet: true

# -------------------------------------------------------

- name: Start configure_server action...
  ansible.builtin.include_tasks: configure_server.yml
  when: action == "configure_server"

- name: Start configure_vault action...
  ansible.builtin.include_tasks: configure_vault.yml
  when: action == "configure_vault"

- name: Start initialize action...
  ansible.builtin.include_tasks: initialize.yml
  when: action == "initialize"

