--- 

- name: Set wait
  ansible.builtin.set_fact:
    wait: false
  when: wait is not defined

- name: Verify variable input
  ansible.builtin.assert:
    that:
      - action is defined and action in actions
    fail_msg: "Please provide 'action' {{ actions }}"
    quiet: true

- name: Configure server
  ansible.builtin.include_tasks: configure_server.yml
  when: action == "configure_server"

- name: Configure vault
  ansible.builtin.include_tasks: configure_vault.yml
  when: action == "configure_vault"
