---

#########################################################
## Platform check                                      ##
#########################################################

# Gather installed packages
- name: Gather installed packages...
  ansible.builtin.package_facts:
    manager: auto

# Set platform if podman is detected
- name: Set platform if podman is detected
  ansible.builtin.set_fact:
    platform: "podman"
  when:
    - '"podman" in ansible_facts.packages'

# Set platform if kubernetes is detected
- name: Set platform if kubernetes is detected
  ansible.builtin.set_fact:
    platform: "kubernetes"
  when:
    - '"kubernetes" in ansible_facts.packages'

# Set platform to host if no podman or no kubernetes is detected
- name: Set platform to host if no Podman or Kubernetes is detected
  ansible.builtin.set_fact:
    platform: "host"
  when:
    - '"podman" not in ansible_facts.packages'
    - '"kubernetes" not in ansible_facts.packages'
